window.CONTENT_SETS = {
    "CVC (a) and CVCE (a)": [
        "The man has a cane.",
        "The cat has a name.",
        "The lad has a cake.",
        "The dad has a rake.",
        "The bag has tape.",
        "The rat has a cage.",
        "The cat is on the gate.",
        "The map is on the case.",
        "The cap is on a rake.",
        "The bag is on the gate.",
        "The fan is on a base.",
        "The bat is on the gate.",
        "A rat is on the cake.",
        "A cap is on the cane.",
        "A map is on the gate.",
        "A cat is on the lane.",
        "A bag is on the base.",
        "The bat is in the cave.",
        "The rat is in the cage.",
        "The man is in the lane.",
        "The map is in a case.",
        "The pan is in the lake.",
        "The lad is in the cave.",
        "A cat is in the lane.",
        "A fan is in the cave.",
        "A bat is in the cage.",
        "A cap is in the lake."
    ],
    "CVC (a,i) and CVCE (a,i)": [
        "The kid has a bike.",
        "The pig has a pipe.",
        "The dad has a file.",
        "The man has a dime.",
        "The rat has a lime.",
        "The kid has a cape.",
        "The pig has a cake.",
        "The wife has a fan.",
        "The pin is on the gate.",
        "The wig is on the rake.",
        "The fig is on the case.",
        "The bib is on the line.",
        "The lid is on the file.",
        "The lime is on the mat.",
        "The dime is on the pad.",
        "The kite is on the van.",
        "The pine is on the map.",
        "A pin is on the tile.",
        "A wig is on the cane.",
        "The pig is in the lake.",
        "The kid is in the cave.",
        "The pin is in the pipe.",
        "The fig is in the pile.",
        "The bat is in the pine.",
        "The rat is in the vine.",
        "The bike is in the van.",
        "The kite is in the bin.",
        "The dime is in the bag.",
        "The file is in the bag.",
        "A pig is in the cage."
    ],
    "CVC (a,i,o) and CVCE (a,i,o)": [
        "The dog has a bone.",
        "The fox has a home.",
        "The cop has a code.",
        "The mom has a rose.",
        "The box has a rope.",
        "The man has a robe.",
        "The cat has a home.",
        "The pig has a nose.",
        "The dad has a vote.",
        "The kid has a cone.",
        "The dog has a name.",
        "The mom has a bike.",
        "The rod is on the cone.",
        "The pot is on the pole.",
        "The mop is on the tile.",
        "The log is on the pile.",
        "The dog is on the rope.",
        "The fox is on the case.",
        "The box is on the line.",
        "The hog is on the gate.",
        "The bone is on the mat.",
        "The cone is on the box.",
        "The rose is on the bed.",
        "The note is on the pad.",
        "A pot is on the stove.",
        "A dog is on the lane.",
        "A fox is on the dike.",
        "The dog is in the hole.",
        "The fox is in the zone.",
        "The box is in the cave.",
        "The rod is in the lake.",
        "The bone is in the pan.",
        "The note is in the box.",
        "A dog is in the home.",
        "A fox is in the cage."
    ]
};

window.CLASSES = {
    "寒假班_CVCE_1630_1800": {
        label: "寒假班 CVCE 16:30-18:00",
        contentSets: ["CVC (a,i,o) and CVCE (a,i,o)"]
    }
};
